### ISSUE TITLE
Underscore is already a taken library name

### ISSUE THREAD

**Issue by lyneca** [thewrongjames/_#1]
[underscore.js](http://underscorejs.org) is a very popular JavaScript library. To avoid copyright claims, you should rename your repository.

**Comment by The-CORE** [comment]
I even tried to check for stuff like that. Thanks for telling me. I will try to think of another name.

**Comment by lyneca** [comment]
you disgust me

**Comment by lyneca** [comment]
(sarcasm don't bother)

**Comment by The-CORE** [comment]
Actually, now that I think about it, I am certainly not infringing copyright, I would have to be stealing intellectual property for that to be the case. Also, even if they owned the trade mark, I am pretty sure that oracle owns the trademark for JavaScript, and that hasn't seemed to bother them.

**Comment by The-CORE** [comment]
Avoiding ambiguity is a good thing, but, at the moment, I have no other name ideas (part of the reason '_' was chosen), so, I don't think I will change it now.

**Comment by lyneca** [comment]
this was a joke

**Comment by The-CORE** [comment]
Ah.
